import { StyleSheet } from "react-native";
import { theme } from "@/style/ui/Theme";
import { vw } from "@/helpers/viewport";

const styles = StyleSheet.create({
  container: {
    position: "relative",
    flexDirection: "row",
    width: "100%",
    height: vw(48),
    marginBottom: theme.padding.large,
    backgroundColor: theme.colors.darkGrey,
    borderRadius: theme.borderRadius.large,
    overflow: "hidden",
    boxShadow: [
      {
        color: theme.colors.shadowDark,
        offsetX: 8,
        offsetY: 8,
        blurRadius: "12px",
      },
    ],
  },
  imageContainer: {
    position: "absolute",
    zIndex: 1,
    top: 0,
    left: 0,
    width: vw(125) - theme.padding.medium * 2,
    height: (vw(125) - theme.padding.medium * 2) * 1.395,
  },
  imageOverlay: {
    position: "absolute",
    width: "100%",
    height: "100%",
    borderRadius: theme.borderRadius.large,
    overflow: "hidden",
    zIndex: 2,
    top: 0,
    left: 0,
  },
  image: {
    position: "absolute",
    width: vw(125) - theme.padding.medium * 2,
    height: (vw(125) - theme.padding.medium * 2) * 1.395,
    top: -vw(27.5),
    left: -vw(12.5),
  },
  mainContainer: {
    position: "relative",
    zIndex: 3,
    width: "100%",
    flexDirection: "row",
    padding: theme.padding.medium,
  },
  watchlistName: {
    width: "50%",
    maxWidth: "50%",
    minWidth: "50%",
    flexGrow: 0,
    flexShrink: 0,
  },
  watchlistButtons: {
    width: "50%",
    maxWidth: "50%",
    minWidth: "50%",
    flexGrow: 0,
    flexShrink: 0,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    flexDirection: "column",
  },
  deleteButton: {
    position: "absolute",
    width: vw(12),
    height: vw(12),
    right: theme.padding.xsmall * 0.5,
    bottom: theme.padding.small * 0.5,
    zIndex: 10,
    borderRadius: theme.borderRadius.xlarge,
    padding: 2,
    backgroundColor: theme.colors.mediumGrey,
    borderWidth: 1,
    borderColor: theme.colors.green,
    ...theme.shadow,
  },
  button: {
    position: "relative",
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  background: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: vw(12),
    height: vw(12),
    borderRadius: theme.borderRadius.xlarge,
    zIndex: 0,
  },
  iconContainerStyle: {
    width: theme.padding.large * 0.75,
    height: theme.padding.large * 0.75,
  },
});

export default styles;
